title: PrOMMiS
author: PrOMMiS Contributors

execute:
  execute_notebooks: "off"
sphinx:
  extra_extensions:
  - sphinx.ext.autodoc
  - sphinx.ext.napoleon
  - sphinx.ext.viewcode
  - sphinx.ext.autosummary
  config:
    autosummary_generate: true